# Generated by Django 5.1.2 on 2025-04-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_status_order_orderitem_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='cost',
            new_name='price',
        ),
    ]
